//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteEmpresa.Banco_de_Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class cadastro
    {
        public string nome_usuario { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public string endereco { get; set; }
        public string adicional { get; set; }
    
        public virtual cadastro cadastro1 { get; set; }
        public virtual cadastro cadastro2 { get; set; }
    }
}
