//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteEmpresa.Banco_de_Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public int id_cliente { get; set; }
        public string nome_cliente { get; set; }
        public string endereco { get; set; }
        public string cartao { get; set; }
        public int idade { get; set; }
    }
}
