//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteEmpresa.Banco_de_Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos_entregues
    {
        public int id { get; set; }
        public string produto { get; set; }
        public double preco { get; set; }
    }
}
